[mainConfig]
appName = "GopherAI"
host = "0.0.0.0"
port = 9090

[redisConfig]
enabled = true    # 是否启用 Redis，设为 false 则使用内存缓存 BigCache
host = "127.0.0.1"
port = 6379
password = ""
db = 0

[mysqlConfig]
host = "127.0.0.1"
port = 3306
user = "root"
password = "123456"
databaseName = "GopherAI"
charset =  "utf8mb4"

[jwtConfig]
 expire_duration= 8760
 issuer= "huanheart"
 subject= "GopherAI"
 key= "GopherAI-v1"

 [ragModelConfig]
  embeddingModel= "text-embedding-v4"
  chatModelName="qwen-turbo"
  docDir = "./docs"
  baseUrl="https://dashscope.aliyuncs.com/compatible-mode/v1"
  dimension=1024

[imageConfig]
  enabled = true                                              # 是否启用图像识别功能
  onnxRuntimeLib = "../onnxruntime-win-x64-1.23.2/lib/onnxruntime.dll"  # ONNX Runtime 动态库路径
  modelPath = "./models/mobilenetv2-7.onnx"                   # 模型文件路径
  labelPath = "./models/synset.txt"                           # 标签文件路径
